---
- name: Download Node Exporter tar.gz
  ansible.builtin.get_url:
    url: "{{ node_exporter_releases_url }}/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/home/ansible/node_exporter-{{ node_exporter_version }}.tar.gz"

- name: Unarchive node_exporter.tar.gz
  ansible.builtin.unarchive:
    src: "/home/ansible/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: "/home/ansible/"
    remote_src: true

- name: Copy node exporter bin file
  ansible.builtin.copy:
    src: "/home/ansible/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/bin/node_exporter
    remote_src: true

- name: Add node exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    home: "{{ node_exporter_home_path }}"
    shell: /usr/bin/false

- name: Chown node_exporter bin file
  ansible.builtin.file:
    path: /usr/bin/node_exporter
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: "0755"

- name: Generate Node Exporter service
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start and enable node_exporter.service
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
...