---
- name: Add Grafana user
  ansible.builtin.user:
    name: grafana
    group: grafana
    home: "{{ grafana_home }}"
    shell: /usr/bin/false

- name: Download Grafana`s archive
  ansible.builtin.get_url:
    url: "{{ grafana_download_url }}"
    dest: "{{ grafana_home }}/grafana.tar.gz"
    mode: "0755"

- name: Unarchive Grafana
  ansible.builtin.unarchive:
    src: "{{ grafana_home }}/grafana.tar.gz"
    dest: "{{ grafana_home }}/grafana_service"

# Доделать: разобраться с файлами графаны и как запустить её как сервис

- name: Enable and start Grafana
  ansible.builtin.systemd:
    name: grafana
    state: started
    enabled: true
    daemon_reload: true
...


# ---
# - name: Install dependencies
#   ansible.builtin.apt:
#     name: "{{ item }}"
#     state: present
#   loop:
#   - "apt-transport-https"
#   - "software-properties-common"
#   - "wget"

# - name: Add Grafana repository key
#   ansible.builtin.apt_key:
#     url: https://apt.grafana.com/gpg.key
#     state: present

# - name: Add Grafana repository
#   ansible.builtin.apt_repository:
#     repo: deb https://apt.grafana.com beta main
#     state: present

# - name: Install Grafana
#   ansible.builtin.apt:
#     name: grafana
#     state: present

# - name: Enable and start Grafana
#   ansible.builtin.service:
#     name: grafana
#     state: started
#     enabled: true
# ...