---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Removing unnecessary packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
  - "docker.io"
  - "docker-compose"
  - "docker-compose-v2"
  - "docker-doc"
  - "podman-docker"

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
  - "docker-buildx-plugin"
  - "docker-compose-plugin"

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
...